# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.enhancd]
git = "https://github.com/Marin-Kitagawa/enhancd"

[plugins.send]
git = "https://github.com/robertzk/send.zsh"

[plugins.fzf-marks]
git = "https://github.com/urbainvaes/fzf-marks"

[plugins.zsh-functional]
git = "https://github.com/Tarrasch/zsh-functional"

[plugins.F-Sy-H]
git = "https://github.com/z-shell/F-Sy-H"

[plugins.history-search-multi-word]
git = "https://github.com/zdharma-continuum/history-search-multi-word"

[plugins.zsh-autosuggestions]
git = "https://github.com/zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
git = "https://github.com/zsh-users/zsh-syntax-highlighting"

[plugins.zsh-shift-select]
git = "https://github.com/jirutka/zsh-shift-select"

[plugins."calc.plugin.zsh"]
git = "https://github.com/arzzen/calc.plugin.zsh"

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
